### ISSUE TITLE
Version 0.14.3 release is missing nested stub content

### ISSUE THREAD

**Issue by phil-airship** [sbdchd/mongo-types#58]
Installing the 0.14.3 does not properly install the various stubs it includes, just general info about mongo-types.

if you look in Pypi at 0.14.3 vs 0.14.2 you can see the large size difference between the Wheels
https://pypi.org/project/mongo-types/0.14.2/#files
https://pypi.org/project/mongo-types/#files

**Comment by sbdchd** [comment]
Ah I bungled it

related: https://github.com/sbdchd/celery-types/issues/40

**Comment by sbdchd** [comment]
Should be fixed in 0.15.0

**Comment by phil-airship** [comment]
Can confirm fix
